<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRn9n5la\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRn9n5la/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRn9n5la.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRn9n5la\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRn9n5la\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rn9n5la',
    'container.build_id' => 'f758f4ea',
    'container.build_time' => 1724783823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRn9n5la');
